import { SystemConfig } from '../types';

export const DEFAULT_CONFIG: SystemConfig = {
  storeName: 'SIIFMART',
  currency: 'ETB',
  taxRate: 0,
  lowStockThreshold: 10,
  fefoRotation: true,
  bayScan: false,
  enableLoyalty: true,
  enableWMS: true,
  multiCurrency: false,
  requireShiftClosure: true,
  posDigitalReceipts: true,
  posAutoPrint: false,
  posReceiptHeader: 'SIIFMART RETAIL',
  posReceiptFooter: 'Thank you for shopping with us!',
  posReceiptLogo: 'https://siifmart.com/logo.png',
  posReceiptShowLogo: true,
  posReceiptAddress: 'Addis Ababa, Ethiopia',
  posReceiptPhone: '+251 911 223 344',
  posReceiptEmail: 'contact@siifmart.com',
  posReceiptTaxId: 'TIN-0012345678',
  posReceiptPolicy: 'No refunds after 7 days without receipt.',
  posReceiptSocialHandle: '@siifmart',
  posReceiptEnableQR: true,
  posReceiptQRLink: 'https://siifmart.com/feedback',
  posReceiptFont: 'sans-serif',
  posTerminalId: 'POS-01',
  fiscalYearStart: '2024-01-01',
  accountingMethod: 'cash',
  language: 'en',
  warehouseBonusEligibility: {},
  posBonusEligibility: {},
  taxJurisdictions: []
};
