// Default fallback for useData() when called outside DataProvider
// This prevents crashes during initial render or provider setup

import { DataContextType } from './DataContext';
import { DEFAULT_CONFIG } from './DataContextDefaults';

export const DATA_CONTEXT_FALLBACK: DataContextType = {
  settings: DEFAULT_CONFIG,
  products: [],
  orders: [],
  suppliers: [],
  sales: [],
  expenses: [],
  movements: [],
  employees: [],
  customers: [],
  shifts: [],
  heldOrders: [],
  sites: [],
  activeSite: undefined,
  notifications: [],
  systemLogs: [],
  promotions: [],
  tasks: [],
  setTasks: () => { },
  allProducts: [],
  allSales: [],
  allOrders: [],
  setProducts: () => { },
  setAllProducts: () => { },
  setOrders: () => { },
  setAllOrders: () => { },
  setSales: () => { },
  setAllSales: () => { },
  updateSettings: () => { },
  setActiveSite: () => { },
  addSite: () => { },
  updateSite: () => { },
  deleteSite: () => { },
  getTaxForSite: () => [],
  addProduct: async () => undefined,
  updateProduct: async () => undefined,
  updatePricesBySKU: async () => { },
  deleteProduct: async () => { },
  relocateProduct: async () => { },
  cleanupAdminProducts: async () => { },
  cleanupDuplicateLocations: async () => { },
  createPO: async () => undefined,
  updatePO: async () => { },
  deletePO: () => { },
  processSale: async () => ({ saleId: '' }),
  processReturn: () => { },
  closeShift: () => { },
  startShift: () => { },
  triggerSync: () => { },
  posCheckQueue: async () => { },
  addSupplier: () => { },
  adjustStock: () => { },
  addExpense: () => { },
  deleteExpense: () => { },
  processPayroll: () => { },
  addEmployee: () => { },
  updateEmployee: () => { },
  deleteEmployee: () => { },
  storePoints: [],
  getStorePoints: () => undefined,
  awardStorePoints: () => { },
  calculateWorkerBonusShare: () => undefined,
  getStoreLeaderboard: () => [],
  addCustomer: () => { },
  updateCustomer: () => { },
  deleteCustomer: () => { },
  holdOrder: () => { },
  releaseHold: () => { },
  addNotification: () => { },
  clearNotification: () => { },
  clearAllNotifications: () => { },
  markNotificationsRead: () => { },
  logSystemEvent: () => { },
  exportSystemData: () => '',
  resetData: () => { },
  refreshData: async () => { },
  addPromotion: () => { },
  deletePromotion: () => { },
  discountCodes: [],
  addDiscountCode: () => { },
  updateDiscountCode: () => { },
  deleteDiscountCode: () => { },
  validateDiscountCode: () => ({ valid: false }),
  useDiscountCode: () => { },
  releaseOrder: async () => { },
  isDataInitialLoading: true,
  loadError: null,
  loadingProgress: { total: 0, loaded: 0, current: '', entities: {} },
  posSyncStatus: 'synced',
  posPendingSyncCount: 0
} as unknown as DataContextType;
