/**
 * Barcode Number Generator Utility
 * Generates valid EAN-13 and internal barcode NUMBERS for products
 * This is different from barcodeGenerator.ts which RENDERS barcodes visually
 */

// EAN-13 check digit calculator (Modulo 10 algorithm)
export const calculateEAN13CheckDigit = (first12: string): number => {
    if (first12.length !== 12 || !/^\d+$/.test(first12)) {
        throw new Error('Input must be exactly 12 digits');
    }

    let sum = 0;
    for (let i = 0; i < 12; i++) {
        const digit = parseInt(first12[i], 10);
        sum += i % 2 === 0 ? digit : digit * 3;
    }

    const checkDigit = (10 - (sum % 10)) % 10;
    return checkDigit;
};

// Generate a valid EAN-13 barcode number
// Uses internal prefix 200-299 (reserved for internal/in-store use in retail)
export const generateEAN13 = (sequenceNumber: number, prefix: string = '200'): string => {
    // EAN-13 structure: 
    // - Prefix (3 digits): 200-299 reserved for internal use
    // - Sequence (9 digits)
    // - Check digit (1 digit)

    const paddedSequence = sequenceNumber.toString().padStart(9, '0');
    const first12 = prefix + paddedSequence;

    if (first12.length !== 12) {
        throw new Error('Prefix and sequence must equal 12 digits');
    }

    const checkDigit = calculateEAN13CheckDigit(first12);
    return first12 + checkDigit.toString();
};

// Generate a unique internal barcode for products without barcodes
// Creates a valid EAN-13 using the 200 prefix (reserved for internal use)
export const generateInternalBarcode = (products: any[]): string => {
    // Find the highest existing internal barcode sequence
    const internalBarcodes = products
        .filter(p => p.barcode && p.barcode.startsWith('200'))
        .map(p => parseInt(p.barcode.slice(3, 12), 10))
        .filter(n => !isNaN(n));

    const maxSequence = internalBarcodes.length > 0 ? Math.max(...internalBarcodes) : 0;
    const newSequence = maxSequence + 1;

    // Generate with 200 prefix (internal use range)
    return generateEAN13(newSequence, '200');
};

// Alternative: Generate CODE128 style barcode (alphanumeric)
// Format: SIIF-{CATEGORY}-{SEQ}-{CHECKSUM}
// Useful for internal tracking with human-readable codes
export const generateCODE128Barcode = (category: string, products: any[]): string => {
    const catPrefix = (category || 'GEN').slice(0, 3).toUpperCase();

    // Find highest sequence for this category
    const regex = new RegExp(`^SIIF-${catPrefix}-(\\d+)`);
    const sequences = products
        .filter(p => p.barcode && regex.test(p.barcode))
        .map(p => {
            const match = p.barcode.match(regex);
            return match ? parseInt(match[1], 10) : 0;
        })
        .filter(n => !isNaN(n));

    const maxSeq = sequences.length > 0 ? Math.max(...sequences) : 0;
    const newSeq = (maxSeq + 1).toString().padStart(4, '0');

    // Simple checksum (sum of char codes mod 100)
    const baseCode = `SIIF-${catPrefix}-${newSeq}`;
    const checksum = baseCode.split('').reduce((sum, char) => sum + char.charCodeAt(0), 0) % 100;

    return `${baseCode}-${checksum.toString().padStart(2, '0')}`;
};

// Validate EAN-13 barcode
export const isValidEAN13 = (barcode: string): boolean => {
    if (!/^\d{13}$/.test(barcode)) return false;

    const first12 = barcode.slice(0, 12);
    const providedCheckDigit = parseInt(barcode[12], 10);
    const calculatedCheckDigit = calculateEAN13CheckDigit(first12);

    return providedCheckDigit === calculatedCheckDigit;
};

// Detect barcode type from value
export const detectBarcodeType = (barcode: string): 'EAN-13' | 'UPC-A' | 'CODE128' | 'CODE39' | 'QR' | 'OTHER' | null => {
    if (!barcode) return null;

    const clean = barcode.trim();

    // EAN-13: 13 digits
    if (/^\d{13}$/.test(clean)) return 'EAN-13';

    // UPC-A: 12 digits
    if (/^\d{12}$/.test(clean)) return 'UPC-A';

    // UPC-E: 8 digits (compact UPC)
    if (/^\d{8}$/.test(clean)) return 'UPC-A';

    // CODE128/CODE39: Alphanumeric, typically with dashes
    if (/^[A-Z0-9\-]{6,20}$/i.test(clean)) return 'CODE128';

    return 'OTHER';
};

// Check if barcode is internal (generated by our system)
export const isInternalBarcode = (barcode: string): boolean => {
    if (!barcode) return false;
    // Our internal barcodes use:
    // - EAN-13 with 200-299 prefix
    // - CODE128 with SIIF- prefix
    return barcode.startsWith('200') || barcode.startsWith('201') ||
        barcode.startsWith('202') || barcode.startsWith('SIIF-');
};

// Format barcode for display (adds spaces for readability)
export const formatBarcodeForDisplay = (barcode: string): string => {
    if (!barcode) return '';

    if (/^\d{13}$/.test(barcode)) {
        // EAN-13: X XXXXXX XXXXXX
        return `${barcode[0]} ${barcode.slice(1, 7)} ${barcode.slice(7)}`;
    }
    if (/^\d{12}$/.test(barcode)) {
        // UPC-A: XXXXXX-XXXXXX
        return `${barcode.slice(0, 6)}-${barcode.slice(6)}`;
    }
    return barcode;
};

// Suggested barcode based on product source
export const suggestBarcodeStrategy = (hasSupplierBarcode: boolean, supplierBarcode?: string): {
    strategy: 'use_supplier' | 'generate_ean13' | 'generate_code128';
    reason: string;
} => {
    if (hasSupplierBarcode && supplierBarcode && supplierBarcode.trim()) {
        return {
            strategy: 'use_supplier',
            reason: 'Product has an existing barcode from supplier - save as-is'
        };
    }

    return {
        strategy: 'generate_ean13',
        reason: 'No barcode exists - generate internal EAN-13 for scanning'
    };
};
